export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const HOME_VIDEO_SUCCESS = "HOME_VIDEO_SUCCESS";
export const HOME_VIDEO_FAIL = "HOME_VIDEO_FAIL";
export const HOME_VIDEO_REQUEST = "HOME_VIDEO_REQUEST";

export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST";
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL";

export const SELECTED_CHANNEL_REQUEST = "SELECTED_CHANNEL_REQUEST";
export const SELECTED_CHANNEL_SUCCESS = "SELECTED_CHANNEL_SUCCESS";
export const SELECTED_CHANNEL_FAIL = "SELECTED_CHANNEL_FAIL";

export const SELECTED_COMMENTS_REQUEST = "SELECTED_COMMENTS_REQUEST";
export const SELECTED_COMMENTS_SUCCESS = "SELECTED_COMMENTS_SUCCESS";
export const SELECTED_COMMENTS_FAIL = "SELECTED_COMMENTS_FAIL";

export const RELATED_VIDEO_REQUEST = "RELATED_VIDEO_REQUEST";
export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS";
export const RELATED_VIDEO_FAIL = "RELATED_VIDEO_FAIL";

export const SEARCH_VIDEO_REQUEST = "SEARCH_VIDEO_REQUEST";
export const SEARCH_VIDEO_SUCCESS = "SEARCH_VIDEO_SUCCESS";
export const SEARCH_VIDEO_FAIL = "SEARCH_VIDEO_FAIL";


export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";